import { LogSource, Action } from "../generated/prisma";

const seedData = {
    logs: [
        {
            tenant: "tenantA",
            source: LogSource.API,
            ts: new Date(),
            user: "alice",
            eventType: "application",
            eventSubtype: "login",
            action: Action.LOGIN,
            severity: 3,
            http_method: "POST",
            url: "/login",
            status_code: 200,
            src_ip: "10.0.0.5",
            dst_ip: "192.168.1.10",
            raw: {
                event: "login",
                user: "alice",
                http: { method: "POST", path: "/login", status_code: 200 },
            },
            tags: ["api", "auth"],
        },
        {
            tenant: "tenantA",
            source: LogSource.FIREWALL,
            ts: new Date(),
            action: Action.DENY,
            severity: 7,
            src_ip: "192.168.1.20",
            dst_ip: "8.8.8.8",
            protocol: "UDP",
            rule_name: "Block External DNS",
            rule_id: "FW-101",
            reason: "Denied DNS request to external resolver",
            raw: {
                line: "<134>Aug 20 12:44:56 fw01 vendor=demo product=ngfw action=deny src=192.168.1.20 dst=8.8.8.8 spt=5353 dpt=53 proto=udp msg=DNS blocked policy=Block-DNS",
            },
            tags: ["firewall", "dns"],
        },
        {
            tenant: "tenantA",
            source: LogSource.AWS,
            ts: new Date("2025-09-09T11:58:12Z"),
            eventType: "audit",
            eventSubtype: "StartInstances",
            user: "bob",
            src_ip: "203.0.113.25",
            cloud_account_id: "123456789012",
            cloud_region: "us-east-1",
            cloud_service: "ec2.amazonaws.com",
            raw: {
                eventTime: "2025-09-09T11:58:12Z",
                eventName: "StartInstances",
                userIdentity: { userName: "bob" },
                sourceIPAddress: "203.0.113.25",
                awsRegion: "us-east-1",
                eventSource: "ec2.amazonaws.com",
            },
            tags: ["aws", "ec2"],
        },
        {
            tenant: "tenantA",
            source: LogSource.M365,
            ts: new Date("2025-09-09T11:45:00Z"),
            eventType: "audit",
            eventSubtype: "FileAccessed",
            user: "carol@company.com",
            host: "SharePoint",
            raw: {
                CreationTime: "2025-09-09T11:45:00Z",
                Operation: "FileAccessed",
                UserId: "carol@company.com",
                Workload: "SharePoint",
            },
            tags: ["m365", "sharepoint"],
        },
        {
            tenant: "tenantA",
            source: LogSource.AD,
            ts: new Date("2025-09-09T11:40:00Z"),
            eventType: "authentication",
            eventSubtype: "logon",
            action: Action.ALERT,
            user: "dave",
            host: "WIN-SERVER01",
            src_ip: "10.1.1.50",
            raw: {
                TimeCreated: "2025-09-09T11:40:00Z",
                EventID: 4625,
                TargetUserName: "dave",
                ComputerName: "WIN-SERVER01",
                IpAddress: "10.1.1.50",
            },
            tags: ["ad", "winsec"],
        },
        {
            tenant: "tenantA",
            source: LogSource.CROWDSTRIKE,
            ts: new Date("2025-09-09T11:30:00Z"),
            eventType: "malware_detection",
            eventSubtype: "detect",
            action: Action.ALERT,
            severity: 9,
            user: "eve",
            host: "WIN10-PC01",
            src_ip: "10.0.0.99",
            raw: {
                "@timestamp": "2025-09-09T11:30:00Z",
                event_type: "malware_detection",
                event_action: "detect",
                severity: 9,
                user: "eve",
                hostname: "WIN10-PC01",
                local_ip: "10.0.0.99",
            },
            tags: ["crowdstrike", "malware"],
        },
        {
            tenant: "tenantA",
            source: LogSource.NETWORK,
            ts: new Date("2025-09-09T11:25:00Z"),
            eventType: "connection",
            eventSubtype: "http_request",
            action: Action.ALLOW,
            severity: 2,
            src_ip: "192.168.1.50",
            dst_ip: "93.184.216.34",
            protocol: "TCP",
            raw: {
                ts: "2025-09-09T11:25:00Z",
                eventType: "connection",
                eventSubtype: "http_request",
                action: "ALLOW",
                src_ip: "192.168.1.50",
                dst_ip: "93.184.216.34",
                protocol: "TCP",
            },
            tags: ["network", "http"],
        },
    ]
}

export default seedData