import { Action, LogSource, Prisma } from "../../prisma/generated/prisma";

const at = (iso: string) => {
    const d = new Date(iso);
    return { ts: d, createdAt: d };
};

const seedData = {
    logs: [
        {
            tenant: "tenantA",
            source: LogSource.API,
            ...at("2025-08-15T02:20:15Z"),
            action: Action.ALERT,
            severity: 5,
            eventType: "LoginAttempt",
            user: "Swam Yi Phyo",
            ip: "203.0.113.10",
            raw: { reason: "Testing default API log" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantB",
            source: LogSource.API,
            ...at("2025-08-18T09:41:03Z"),
            action: Action.ALERT,
            severity: 4,
            eventType: "LoginAttempt",
            user: "Alice",
            ip: "198.51.100.45",
            raw: { reason: "Suspicious user-agent" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantC",
            source: LogSource.API,
            ...at("2025-08-21T13:03:22Z"),
            action: Action.ALERT,
            severity: 6,
            eventType: "LoginAttempt",
            user: "Bob",
            ip: "192.0.2.77",
            raw: { reason: "Multiple failed attempts" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantA",
            source: LogSource.API,
            ...at("2025-08-27T07:18:49Z"),
            action: Action.ALERT,
            severity: 3,
            eventType: "LoginAttempt",
            user: "Carol",
            ip: "203.0.113.55",
            raw: { reason: "Password reset required" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantB",
            source: LogSource.API,
            ...at("2025-09-03T11:59:10Z"),
            action: Action.ALERT,
            severity: 5,
            eventType: "LoginAttempt",
            user: "David",
            ip: "198.51.100.99",
            raw: { reason: "Testing default API log" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantC",
            source: LogSource.API,
            ...at("2025-09-12T15:20:05Z"),
            action: Action.ALERT,
            severity: 2,
            eventType: "LoginAttempt",
            user: "Eve",
            ip: "203.0.113.200",
            raw: { reason: "Legacy token used" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantA",
            source: LogSource.CROWDSTRIKE,
            ...at("2025-08-16T05:10:00Z"),
            action: Action.ALERT,
            severity: 8,
            eventType: "malware_detected",
            host: "WIN10-01",
            process: "powershell.exe",
            ip: "10.0.0.12",
            raw: {
                sha256:
                    "f3b1a9e7c1d2e9a4cc00112233445566778899aabbccddeeff00112233445500",
            } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantB",
            source: LogSource.CROWDSTRIKE,
            ...at("2025-08-19T14:22:31Z"),
            action: Action.ALERT,
            severity: 9,
            eventType: "malware_detected",
            host: "WIN11-WS02",
            process: "cmd.exe",
            ip: "10.10.5.21",
            raw: {
                sha256:
                    "aa55bb66cc77dd88ee9900ff11223344556677889900aabbccddeeff00112233",
            } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantC",
            source: LogSource.CROWDSTRIKE,
            ...at("2025-08-24T00:44:18Z"),
            action: Action.ALERT,
            severity: 6,
            eventType: "malware_detected",
            host: "SRV-APP-01",
            process: "java.exe",
            ip: "172.16.1.40",
            raw: {
                sha256:
                    "1122aabb3344cc5566778899ddeeff00112233445566778899aabbccddeeff00",
            } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantA",
            source: LogSource.CROWDSTRIKE,
            ...at("2025-08-29T08:05:02Z"),
            action: Action.ALERT,
            severity: 7,
            eventType: "malware_detected",
            host: "LAPTOP-DEV01",
            process: "node.exe",
            ip: "10.0.2.55",
            raw: {
                sha256:
                    "00ffeeddccbbaa99887766554433221100ffeeddccbbaa998877665544332211",
            } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantB",
            source: LogSource.CROWDSTRIKE,
            ...at("2025-09-06T12:26:45Z"),
            action: Action.ALERT,
            severity: 5,
            eventType: "malware_detected",
            host: "WIN10-SEC",
            process: "powershell.exe",
            ip: "10.10.10.10",
            raw: {
                sha256:
                    "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
            } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantC",
            source: LogSource.CROWDSTRIKE,
            ...at("2025-09-11T03:59:59Z"),
            action: Action.ALERT,
            severity: 8,
            eventType: "malware_detected",
            host: "SRV-FILE-02",
            process: "rundll32.exe",
            ip: "172.16.2.88",
            raw: {
                sha256:
                    "cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe",
            } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantA",
            source: LogSource.AWS,
            ...at("2025-08-17T01:15:00Z"),
            action: Action.ALERT,
            severity: 4,
            eventType: "CreateUser",
            user: "Fisheeesh",
            ip: "198.51.100.10",
            raw: { cloud: { service: "iam", account_id: "123456789012", region: "ap-southeast-1" } } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantB",
            source: LogSource.AWS,
            ...at("2025-08-22T11:47:55Z"),
            action: Action.ALERT,
            severity: 5,
            eventType: "StartInstances",
            user: "ops-bot",
            ip: "203.0.113.90",
            raw: { cloud: { service: "ec2", account_id: "123456789012", region: "us-east-1" } } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantC",
            source: LogSource.AWS,
            ...at("2025-08-28T21:09:33Z"),
            action: Action.ALERT,
            severity: 3,
            eventType: "PutBucketAcl",
            user: "auditor",
            ip: "192.0.2.120",
            raw: { cloud: { service: "s3", account_id: "123456789012", region: "eu-west-1" } } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantA",
            source: LogSource.AWS,
            ...at("2025-09-04T02:02:02Z"),
            action: Action.ALERT,
            severity: 6,
            eventType: "AttachRolePolicy",
            user: "admin",
            ip: "203.0.113.33",
            raw: { cloud: { service: "iam", account_id: "123456789012", region: "ap-southeast-1" } } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantB",
            source: LogSource.AWS,
            ...at("2025-09-08T16:40:18Z"),
            action: Action.ALERT,
            severity: 4,
            eventType: "AuthorizeSecurityGroupIngress",
            user: "sec-team",
            ip: "198.51.100.200",
            raw: { cloud: { service: "ec2", account_id: "123456789012", region: "ap-south-1" } } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantC",
            source: LogSource.AWS,
            ...at("2025-09-12T23:55:45Z"),
            action: Action.ALERT,
            severity: 5,
            eventType: "CreateAccessKey",
            user: "devops",
            ip: "192.0.2.88",
            raw: { cloud: { service: "iam", account_id: "123456789012", region: "us-west-2" } } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantA",
            source: LogSource.M365,
            ...at("2025-08-15T09:00:00Z"),
            action: Action.ALERT,
            severity: 3,
            eventType: "UserLoggedIn",
            user: "syp@swe",
            ip: "198.51.100.23",
            raw: { status: "Success", workload: "Exchange" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantB",
            source: LogSource.M365,
            ...at("2025-08-23T18:20:45Z"),
            action: Action.ALERT,
            severity: 2,
            eventType: "FileAccessed",
            user: "alice@tenantb.com",
            ip: "203.0.113.150",
            raw: { status: "Success", workload: "SharePoint" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantC",
            source: LogSource.M365,
            ...at("2025-08-31T03:33:10Z"),
            action: Action.ALERT,
            severity: 4,
            eventType: "MailboxPermissionChanged",
            user: "admin@tenantc.com",
            ip: "192.0.2.13",
            raw: { status: "Modified", workload: "Exchange" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantA",
            source: LogSource.M365,
            ...at("2025-09-02T12:12:12Z"),
            action: Action.ALERT,
            severity: 3,
            eventType: "UserLoggedIn",
            user: "ops@tenanta.com",
            ip: "198.51.100.60",
            raw: { status: "Success", workload: "AzureAD" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantB",
            source: LogSource.M365,
            ...at("2025-09-07T07:07:07Z"),
            action: Action.ALERT,
            severity: 5,
            eventType: "DlpPolicyMatch",
            user: "hr@tenantb.com",
            ip: "203.0.113.77",
            raw: { status: "Blocked", workload: "Exchange" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantC",
            source: LogSource.M365,
            ...at("2025-09-13T08:45:35Z"),
            action: Action.ALERT,
            severity: 2,
            eventType: "UserLoggedIn",
            user: "user@tenantc.com",
            ip: "192.0.2.200",
            raw: { status: "Success", workload: "Teams" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantA",
            source: LogSource.AD,
            ...at("2025-08-17T22:10:00Z"),
            action: Action.ALERT,
            severity: 6,
            eventType: "LogonFailed",
            user: "Chotta Bheem",
            host: "DC01",
            ip: "203.0.113.77",
            raw: { eventId: "4625", logonType: "3" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantB",
            source: LogSource.AD,
            ...at("2025-08-26T04:55:22Z"),
            action: Action.ALERT,
            severity: 5,
            eventType: "KerberosTgtRequest",
            user: "service_acct",
            host: "DC02",
            ip: "198.51.100.11",
            raw: { eventId: "4768", logonType: "3" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantC",
            source: LogSource.AD,
            ...at("2025-09-01T10:30:30Z"),
            action: Action.ALERT,
            severity: 7,
            eventType: "AdminPrivilegeAssigned",
            user: "administrator",
            host: "DC01",
            ip: "192.0.2.33",
            raw: { eventId: "4672", logonType: "2" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantA",
            source: LogSource.AD,
            ...at("2025-09-09T06:16:16Z"),
            action: Action.ALERT,
            severity: 4,
            eventType: "Logoff",
            user: "svc-backup",
            host: "FS01",
            ip: "10.0.0.50",
            raw: { eventId: "4634", logonType: "3" } as Prisma.InputJsonValue,
        },
        {
            tenant: "tenantB",
            source: LogSource.AD,
            ...at("2025-09-12T19:49:00Z"),
            action: Action.ALERT,
            severity: 6,
            eventType: "ExplicitCredentials",
            user: "ops-user",
            host: "APP01",
            ip: "10.10.1.25",
            raw: { eventId: "4648", logonType: "10" } as Prisma.InputJsonValue,
        },
    ]
}

export default seedData